name: CI CD to fargate

on: [push]

jobs:
  deploy-to-fargate:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: $(terraform output -raw region)
      ACCOUNTID: $(terraform output -raw account_id)
      CONTAINER_NAME: $(terraform output -raw ecs_service_name)
      IMAGE_NAME: $(terraform output -raw docker_image)
      SERVICE_NAME: $(terraform output -raw ecs_service_name)
      CLUSTER_NAME: $(terraform output -raw ecs_cluster_name)

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{env.ACCOUNTID}}:role/githubactionsrole
          region: ${{env.AWS_REGION}}

      - name: download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{env.SERVICE_NAME}} --query taskdefinition > task-definition.json

      - name: change task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{env.CONTAINER_NAME}}
          image: ${{env.IMAGE_NAME}}

      - name: deploy new task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{steps.task-def.outputs.task-definition}}
          service: ${{env.SERVICE_NAME}}
          cluster: ${{env.CLUSTER_NAME}}
          wait-for-service-stability: true
